name: release-public-version
on:

  push:
    branches:
      - master
      - main
  workflow_dispatch:


jobs: 
  build: 
    name: setup public repository 
    runs-on: ubuntu-latest

    steps:

      - name: Set up SSH agent
        uses: actions/setup-ssh@v3
        with:
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}


      - name: Clone remote repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: https://github.com/oat-sa/test-private-repo.git
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}      

      - name: create a new branch 
        run: | 
          cd test-private-repo
          git branch 
          git checkout -b public-version
          git status 
          ls -al 

      - name: remove secret files 
        run: |
          git branch 
          git rm -r infra
          git rm -r docker 
          git add * 
          git commit -m "fix: testing"

      - name: push to public repository 
        run: |
          git remote add public git@github.com:oat-sa/test-public1-repo.git
          git remote -v
          git push -u public public-version:develop
  
