name: release-public-version
on:

  push:
    branches:
      - master
      - main
  workflow_dispatch:


jobs: 
  build: 
    name: setup public repository 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: create a new branch 
        run: | 
          git config --global user.name "edwin-focaloid"
          git config --global user.email "edwin.sany@focaloid.com"  
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa  
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa    
          git clone git@github.com:oat-sa/test-private-repo.git
          cd test-private-repo
          git branch 
          git checkout -b public-version
          git status 
          ls -al 

      - name: remove secret files 
        run: |
          git branch 
          git rm -r infra
          git rm -r docker 
          git add * 
          git commit -m "fix: testing"

      - name: push to public repository 
        run: |
          git remote add public git@github.com:oat-sa/test-public1-repo.git
          git remote -v
          git push -u public public-version:develop
  
